### GET request to example server
POST localhost:4004/api/v1/schedule-template
Content-Type: application/json

{
  "dayOfWeek": [
    "MONDAY", "TUESDAY", "WEDNESDAY","THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"
  ],
  "fromTime": "08:00",
  "toTime": "12:00",
  "slotDuration": 20
}
###