### GET request to example server
POST http://localhost:8082/api/v1/schedules/0ea89ed0-5b11-4f9c-9c29-deb8f9ca2c41
Content-Type: application/json

{
  "dayOfWeek": [
    "MONDAY", "TUESDAY", "WEDNESDAY","THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"
  ],
  "fromTime": "08:00",
  "toTime": "12:00",
  "slotDuration": 20
}
###