### GET request to example server
POST http://localhost:8082/api/v1/schedules/eb47d496-eb92-438a-a697-705a9a371b0
Content-Type: application/json

{
  "dayOfWeek": [
    "MONDAY", "TUESDAY", "WEDNESDAY","THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"
  ],
  "fromTime": "08:00",
  "toTime": "12:00",
  "slotDuration": 30
}
###