### POST request to create Doctor
POST http://localhost:8080/api/v1/doctors
Content-Type: application/json

{
  "userId": "f6ff47d1-03a8-4ccd-8f06-9276b8c932b4",
  "fullName": "Tran Minh Dang",
  "address": "123 An Duong Vuong"
}
###