server:
  port: 4004 # Gateway listens on port 4004

auth:
  service:
    url: http://localhost:8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Route for /api/v1/auth/** to auth-service
          - id: auth-service-route
            uri: http://localhost:8080
            predicates:
              - Path=/api/v1/auth/**
            filters:
              - StripPrefix=0

            # Route for /api/v1/users/** to users-service
          - id: user-service-route
            uri: http://localhost:8080
            predicates:
              - Path=/api/v1/users/**
            filters:
              - StripPrefix=0
              - JwtValidation

            # Route for /api/v1/profile/** to users-service
          - id: profile-service-route
            uri: http://localhost:8080
            predicates:
              - Path=/api/v1/profile/**
            filters:
              - StripPrefix=0
              - JwtValidation

            # Route for /api/v1/doctor-available-slots/** to doctor-available-slots
          - id: doctor-available-slots-service-route
            uri: http://localhost:8082
            predicates:
              - Path=/api/v1/doctor-available-slots/**
            filters:
              - StripPrefix=0
              - JwtValidation

            # Route for /api/v1/schedule-template/** to schedule-template
          - id: schedule-template-service-route
            uri: http://localhost:8082
            predicates:
              - Path=/api/v1/schedule-template/**
            filters:
              - StripPrefix=0
              - JwtValidation