server:
  port: 4004 # Gateway listens on port 4004

auth:
  service:
    url: http://localhost:8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: auth-service
            uri: http://localhost:8080
            predicates:
              - Path=/api/v1/auth/**
            filters:
              - StripPrefix=0

  #        # Route for /api/v1/users/** to users-service
          - id: user-service-route
            uri: http://localhost:8080
            predicates:
              - Path=/api/v1/users/**
            filters:
              - StripPrefix=1
              - JwtValidation
