#server:
#  port: 4004 # Gateway listens on port 4004
#
#auth:
#  service:
#    url: http://auth-service:8080
#
#spring:
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            # Route for /api/v1/auth/** to auth-service
#          - id: auth-service-route
#            uri: http://auth-service:8080
#            predicates:
#              - Path=/api/v1/auth/**
#
#            # Route for /api/v1/users/** to users-service
#          - id: user-service-route
#            uri: http://auth-service:8080
#            predicates:
#              - Path=/api/v1/users/**
#            filters:
#              - JwtValidation
#
#            # Route for /api/v1/profile/** to users-service
#          - id: profile-service-route
#            uri: http://auth-service:8080
#            predicates:
#              - Path=/api/v1/profile/**
#            filters:
#              - JwtValidation#

#            # Route for /api/v1/clinics/** to users-service
#          - id: clinics-service-route
#            uri: http://auth-service:8080
#            predicates:
#              - Path=/api/v1/clinics/**
#            filters:
#              - JwtValidation
#
#            # Route for /api/v2/clinics/**
#          - id: clinic-service-route
#            uri: http://clinic-service:8081
#            predicates:
#            - Path=/api/v2/clinics/**
#
#            # Route for /api/v2/specialties/**
#          - id: specialties-service-route
#            uri: http://clinic-service:8081
#            predicates:
#              - Path=/api/v2/specialties/**
#            filters:
#              - JwtValidation
#
#            # Route for /api/v2/clinic-specialty/**
#          - id: clinic-specialty-service-route
#            uri: http://clinic-service:8081
#            predicates:
#              - Path=/api/v2/clinic-specialty/**
#            filters:
#              - JwtValidation

#            # Route for /api/v2/doctor-specialty/**
#          - id: doctor-specialty-service-route
#            uri: clinic-service:8081
#            predicates:
#              - Path=/api/v2/doctor-specialty/**
#            filters:
#              - JwtValidation

#            # Route for /api/v2/doctors/**
#          - id: doctors-service-route
#            uri: clinic-service:8081
#            predicates:
#              - Path=/api/v2/doctors/**

#            # Route for /api/v2/clinic-invitation/**
#          - id: clinic-invitation-service-route
#            uri: clinic-invitation-service:8081
#            predicates:
#              - Path=/api/v2/clinic-invitation/**
#            filters:
#              - JwtValidation
#
#            # Route for /api/v3/doctor-template/** to doctor-available-slots
#          - id: doctor-schedule-template-service-route
#            uri: http://schedule-service:8082
#            predicates:
#              - Path=/api/v3/doctor-schedule-template/**
#            filters:
#              - JwtValidation
#
#            # Route for /api/v3/clinic-specialty/** to doctor-available-slots
#          - id: clinic-specialty-schedule-template-service-route
#            uri: http://schedule-service:8082
#            predicates:
#              - Path=/api/v3/clinic-specialty-schedule-template/**
#            filters:
#              - JwtValidation
#
#          - id: schedule-doctor-service-route
#            uri: http://schedule-service:8082
#            predicates:
#              - Path=/api/v3/schedule/doctor/**

#          - id: schedule-clinic-specialty-service-route
#            uri: http://schedule-service:8082
#            predicates:
#              - Path=/api/v3/schedule/clinic-specialty/**

server:
  port: 4004 # Gateway listens on port 4004

auth:
  service:
    url: http://localhost:8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Route for /api/v1/auth/** to auth-service
          - id: auth-service-route
            uri: http://localhost:8080
            predicates:
              - Path=/api/v1/auth/**

            # Route for /api/v1/users/** to users-service
          - id: user-service-route
            uri: http://localhost:8080
            predicates:
              - Path=/api/v1/users/**
            filters:
              - JwtValidation

            # Route for /api/v1/profile/** to users-service
          - id: profile-service-route
            uri: http://localhost:8080
            predicates:
              - Path=/api/v1/profile/**
            filters:
              - JwtValidation

          - id: appointment-info-service-route
            uri: http://localhost:8080
            predicates:
              - Path=/api/v1/appointments/appointment-info/**
            filters:
              - JwtValidation

          - id: clinic-specialty-info-service-route
            uri: http://localhost:8081
            predicates:
              - Path=/api/v2/appointments/clinic-specialty-info/**
            filters:
              - JwtValidation

            # Route for /api/v2/clinics/**
          - id: clinic-service-route
            uri: http://localhost:8081
            predicates:
            - Path=/api/v2/clinics/**

            # Route for /api/v2/specialties/**
          - id: specialties-service-route
            uri: http://localhost:8081
            predicates:
              - Path=/api/v2/specialties/**
            filters:
              - JwtValidation

            # Route for /api/v2/clinic-specialty/**
          - id: clinic-specialty-service-route
            uri: http://localhost:8081
            predicates:
              - Path=/api/v2/clinic-specialty/**
            filters:
              - JwtValidation

            # Route for /api/v2/doctor-specialty/**
          - id: doctor-specialty-service-route
            uri: http://localhost:8081
            predicates:
              - Path=/api/v2/doctor-specialty/**
            filters:
              - JwtValidation

            # Route for /api/v2/doctors/**
          - id: doctors-service-route
            uri: http://localhost:8081
            predicates:
              - Path=/api/v2/doctors/**

            # Route for /api/v2/clinic-invitation/**
          - id: clinic-invitation-service-route
            uri: http://localhost:8081
            predicates:
              - Path=/api/v2/clinic-invitation/**
            filters:
              - JwtValidation

            # Route for /api/v3/doctor-schedule-template/** to doctor-available-slots
          - id: schedule-template-service-route
            uri: http://localhost:8082
            predicates:
              - Path=/api/v3/doctor-schedule-template/**
            filters:
              - JwtValidation

            # Route for /api/v3/clinic-specialty-schedule-template/** to doctor-available-slots
          - id: clinic-specialty-template-service-route
            uri: http://localhost:8082
            predicates:
              - Path=/api/v3/clinic-specialty-schedule-template/**
            filters:
              - JwtValidation

          - id: schedule-doctor-service-route
            uri: http://localhost:8082
            predicates:
              - Path=/api/v3/schedule/doctor/**

          - id: appointment-data-service-route
            uri: http://localhost:8082
            predicates:
              - Path=/api/v3/appointments/**
            filters:
              - JwtValidation

          - id: schedule-clinic-specialty-service-route
            uri: http://localhost:8082
            predicates:
              - Path=/api/v3/schedule/clinic-specialty/**
